import { TUTORIAL_TARGETS } from './drumsTutorialConstants.js';
import { TUTORIAL_STEP_IDS } from './tutorialStepIds.js';

const DRUMS_TUTORIAL_STEPS = Object.freeze([
  {
    id: TUTORIAL_STEP_IDS.OPENING,
    phase: 'Opening',
    title: '开场最高任务',
    trigger: '用户进入正式操作前',
    copy: '你将像搭积木一样创作一段独属于你的音乐片段',
    uiMode: 'opening-key-message',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.START_CTA,
    phase: 'Start CTA',
    title: '进入主界面',
    trigger: '用户点击开始按钮',
    copy: '开始创造',
    uiMode: 'primary-cta',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.UI_TOP_BAR,
    phase: 'UI Tour',
    title: 'Top Bar 介绍',
    trigger: 'Top Bar 被 Highlight',
    copy: '在这里，你可以调整你的音轨整体参数或设置循环播放',
    uiMode: 'target-popover',
    target: { name: TUTORIAL_TARGETS.TOP_BAR },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.UI_TRACK_AREA,
    phase: 'UI Tour',
    title: '全局音轨区介绍',
    trigger: '全局音轨区被 Highlight',
    copy: '在这里，你可以对操作构成你的乐曲的每个音轨，并可以拖动进度条到你想要的位置',
    uiMode: 'target-popover',
    target: { name: TUTORIAL_TARGETS.TRACK_AREA },
    completion: { type: 'track-area-tour', trackId: 'drums', bar: 0 },
  },
  {
    id: TUTORIAL_STEP_IDS.UI_EDITOR,
    phase: 'UI Tour',
    title: '音轨编辑区介绍',
    trigger: '音轨编辑区被 Highlight',
    copy: '在这里，详细地编辑各个音轨，获取你想要的声音效果',
    uiMode: 'target-popover',
    target: { name: TUTORIAL_TARGETS.TRACK_EDITOR },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_OPENING,
    phase: 'Drums Setup',
    title: '第一个任务开场',
    trigger: 'UI 区域介绍结束后',
    copy: '让我们从零开始设计一段打击乐律动——这是你的音乐的地基',
    uiMode: 'task-prompt',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_AUTOFILL,
    phase: 'Drums Setup',
    title: '自动生成基础律动',
    trigger: '打击乐音轨出现后',
    copy: '每个人的生命里都会听到的律动：动次打次🥁',
    uiMode: 'task-prompt',
    setup: { type: 'generate-initial-drums' },
    playback: { bars: [0, 1, 2, 3], autoStart: true },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_1_INTRO,
    phase: 'Drums Task 1',
    title: '任务1引导',
    trigger: '基础律动播放后',
    copy: '但简单的改造，就会让它听起来惊喜满满。来试试看！',
    uiMode: 'task-prompt',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_1,
    phase: 'Drums Task 1',
    title: '任务1《动次打次》',
    trigger: '四个节奏乐句 block 与可点击格子开始闪烁',
    copy: '任务1《动次打次》：在第2小节的闪烁位置增加两个底鼓音符（0/2）',
    progressCopy: '在第2小节的闪烁位置增加两个底鼓音符',
    uiMode: 'task-progress',
    completion: { type: 'drums-task-1' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_1_COMPLETE,
    phase: 'Drums Task 1',
    title: '任务1完成',
    trigger: '用户完成 2 个底鼓音符后',
    copy: '干得好👍，现在听听看这两个音符带来了什么不同👀',
    uiMode: 'completion-feedback',
    playback: { bars: [0, 1, 2, 3], autoStart: true },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_1_FEEDBACK,
    phase: 'Drums Task 1',
    title: '任务1回放后',
    trigger: '四小节回放结束',
    copy: '感觉到不同了吗？😉',
    uiMode: 'task-prompt',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_2_INTRO,
    phase: 'Drums Task 2',
    title: '任务2转场',
    trigger: '任务1反馈后',
    copy: '它还能更好玩——',
    uiMode: 'task-prompt',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_2,
    phase: 'Drums Task 2',
    title: '任务2《拖和拽》',
    trigger: '未编辑两小节开始闪烁',
    copy: '任务2《拖和拽》：在第3小节，将底鼓音符向右移动两格（0/1）',
    progressCopy: '在第3小节，将底鼓音符向右移动两格',
    uiMode: 'task-progress',
    completion: { type: 'drums-task-2' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_2_COMPLETE,
    phase: 'Drums Task 2',
    title: '任务2完成',
    trigger: '拖动完成后',
    copy: '简单的拖动，能带来多大改变？🤔听听看就知道了！',
    uiMode: 'completion-feedback',
    playback: { bars: [0, 1, 2, 3], autoStart: true },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_2_FEEDBACK,
    phase: 'Drums Task 2',
    title: '任务2回放后',
    trigger: '四小节回放结束',
    copy: '感觉到你刚才拖拽的那个底鼓音符带来的律动感了吗？💃',
    uiMode: 'task-prompt',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_3_INTRO,
    phase: 'Drums Task 3',
    title: '任务3转场',
    trigger: '任务2反馈后',
    copy: '再来试试最后一种手法——',
    uiMode: 'task-prompt',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_3,
    phase: 'Drums Task 3',
    title: '任务3《循规蹈矩》',
    trigger: '最后一个未编辑小节开始闪烁',
    copy: '任务3《循规蹈矩》：在第4小节中的第5或第13格增加一个底鼓音符（0/1）',
    progressCopy: '在第4小节中的第5或第13格增加一个底鼓音符',
    uiMode: 'task-progress',
    completion: { type: 'drums-task-3' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_3_COMPLETE,
    phase: 'Drums Task 3',
    title: '任务3完成',
    trigger: '点击完成后',
    copy: '在这两个位置增加一个底鼓音符，听起来会更加整齐',
    uiMode: 'completion-feedback',
    playback: { bars: [0, 1, 2, 3], autoStart: true },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_4_INTRO,
    phase: 'Drums Task 4',
    title: '任务4转场',
    trigger: '任务3回放结束',
    copy: '现在，你已经掌握了基础三种创造律动感的手法，现在再来尝试四小节，只通过编辑底鼓音符来创造你的律动！',
    uiMode: 'task-prompt',
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_4,
    phase: 'Drums Task 4',
    title: '任务4《底鼓战士》',
    trigger: '自动增加 4 小节后',
    copy: '任务4《底鼓战士》：根据刚刚掌握的三种手法，自由创作四小节的底鼓音符，满意后点按完成按钮继续',
    uiMode: 'task-with-complete-button',
    setup: { type: 'create-free-drums-bars' },
    completion: { type: 'drums-task-4' },
  },
  {
    id: TUTORIAL_STEP_IDS.DRUMS_TASK_4_COMPLETE,
    phase: 'Drums Complete',
    title: '任务4完成',
    trigger: '用户点击完成按钮后',
    copy: '好玩吧？更好玩的还在后头——',
    uiMode: 'completion-feedback',
    playback: { bars: [0, 1, 2, 3, 4, 5, 6, 7], autoStart: true },
    completion: { type: 'manual' },
  },
]);

export { DRUMS_TUTORIAL_STEPS };
