import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';

const TRACK_IDS = ['drums', 'chord', 'bass', 'melody', 'pad', 'vocal', 'sample'];

test('ui shell keeps the editor usable and confines mobile overflow to panels', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /--app-topbar-height:\s*clamp\(52px,\s*7vh,\s*64px\);/);
  assert.match(css, /--app-editor-height:\s*clamp\(260px,\s*39vh,\s*330px\);/);
  assert.match(css, /--timeline-min-width:\s*min\(640px,\s*100%\);/);
  assert.match(css, /--timeline-clip-y-inset:\s*6px;/);
  assert.match(css, /--timeline-bar-x-inset:\s*4px;/);
  assert.match(css, /\.app\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\);/s);
  assert.match(css, /\.app\s*\{[^}]*height:\s*100dvh;/s);
  assert.match(css, /\.app\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.app-main\s*\{[^}]*grid-template-rows:\s*var\(--app-topbar-height\) minmax\(0,\s*1fr\) var\(--app-editor-height\);/s);
  assert.match(css, /\.workspace\s*\{[^}]*grid-template-columns:\s*clamp\(188px,\s*18vw,\s*246px\) minmax\(0,\s*1fr\);/s);
  assert.match(css, /\.editor\s*\{[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.seq-body\s*\{[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.chord-grid\s*\{[^}]*min-width:\s*0;/s);
  assert.match(css, /grid-template-columns:\s*168px minmax\(0,\s*1fr\);/);
  assert.match(css, /\.stat:nth-child\(4\)\s*\{[^}]*display:\s*none;/s);
});

test('timeline clips fill exactly one bar grid cell', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.clip\s*\{[^}]*left:\s*0;/s);
  assert.match(css, /\.clip\s*\{[^}]*left:\s*calc\(var\(--bar-index\) \* 100% \/ var\(--bars\)\);/s);
  assert.match(css, /\.clip\s*\{[^}]*width:\s*calc\(100% \/ var\(--bars\)\);/s);
  assert.match(css, /\.clip\s*\{[^}]*top:\s*var\(--timeline-clip-y-inset\);/s);
  assert.match(css, /\.clip\s*\{[^}]*bottom:\s*var\(--timeline-clip-y-inset\);/s);
  assert.match(css, /\.clip\s*\{[^}]*box-sizing:\s*border-box;/s);
  assert.match(css, /\.clip\s*\{[^}]*min-width:\s*0;/s);
  assert.match(css, /\.bar-drop-zone\s*\{[^}]*top:\s*var\(--timeline-clip-y-inset\);/s);
  assert.match(css, /\.bar-drop-zone\s*\{[^}]*bottom:\s*var\(--timeline-clip-y-inset\);/s);
  assert.match(css, /\.bar-drop-zone\s*\{[^}]*left:\s*calc\(var\(--bar-index\) \* 100% \/ var\(--bars\) \+ var\(--timeline-bar-x-inset\)\);/s);
  assert.match(css, /\.bar-drop-zone\s*\{[^}]*width:\s*calc\(100% \/ var\(--bars\) - var\(--timeline-bar-x-inset\) - var\(--timeline-bar-x-inset\)\);/s);
  assert.match(css, /\.ruler\s*\{[^}]*grid-template-columns:\s*repeat\(var\(--bars\),\s*minmax\(80px,\s*1fr\)\);/s);
  assert.match(css, /\.ruler\s*\{[^}]*min-width:\s*var\(--timeline-min-width\);/s);
  assert.match(css, /\.grid\s*\{[^}]*min-width:\s*var\(--timeline-min-width\);/s);
  assert.match(css, /\.add-clip\s*\{[^}]*left:\s*calc\(\(var\(--bar-index\) \+ 0\.5\) \* 100% \/ var\(--bars\)\);/s);
  assert.match(css, /\.add-clip\s*\{[^}]*transform:\s*translate\(-50%, -50%\);/s);
  assert.doesNotMatch(css, /\.clip\s*\{[^}]*\+ 10px/s);
  assert.doesNotMatch(css, /\.clip\s*\{[^}]*- 20px/s);
  assert.doesNotMatch(css, /\.clip\s*\{[^}]*top:\s*6px;/s);
  assert.doesNotMatch(css, /\.clip\s*\{[^}]*bottom:\s*6px;/s);
  assert.doesNotMatch(css, /\.bar-drop-zone\s*\{[^}]*top:\s*6px;/s);
  assert.doesNotMatch(css, /\.bar-drop-zone\s*\{[^}]*bottom:\s*6px;/s);
  assert.doesNotMatch(css, /\.clip-mini\s*\{/);
  assert.doesNotMatch(css, /var\(--bars\) \* 1\.55/);
});

test('timeline playhead spans ruler and track grid', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.ruler\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.ruler-playhead,\s*\n\.playhead\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.ruler-playhead,\s*\n\.playhead\s*\{[^}]*width:\s*2px;/s);
  assert.match(css, /\.ruler-playhead\s*\{[^}]*top:\s*0;/s);
  assert.match(css, /\.ruler-playhead\s*\{[^}]*bottom:\s*-1px;/s);
  assert.match(css, /\.ruler-playhead\s*\{[^}]*background:\s*transparent;/s);
  assert.match(css, /\.ruler-playhead::before\s*\{[^}]*position:\s*absolute;[^}]*top:\s*0;[^}]*bottom:\s*8px;[^}]*left:\s*0;[^}]*width:\s*2px;[^}]*pointer-events:\s*none;/s);
  assert.match(css, /\.ruler-playhead::before\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--brand\) 65%,\s*black\);/s);
  assert.match(css, /\.playhead\s*\{[^}]*top:\s*0;/s);
  assert.match(css, /\.playhead\s*\{[^}]*bottom:\s*0;/s);
  assert.match(css, /\.playhead-hit\s*\{[^}]*width:\s*14px;/s);
  assert.match(css, /\.playhead-hit\s*\{[^}]*cursor:\s*ew-resize;/s);
  assert.match(css, /\.playhead-hit\s*\{[^}]*background:\s*transparent;/s);
  assert.match(css, /\.timeline-col\.playhead-dragging\s*\{[^}]*cursor:\s*grabbing;/s);
});

test('editor resize handle overlays the workspace editor boundary', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.app-main\s*\{[^}]*grid-template-rows:\s*var\(--app-topbar-height\) minmax\(0,\s*1fr\) var\(--app-editor-height\);/s);
  assert.match(css, /\.app-main\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.editor-resizer\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.editor-resizer\s*\{[^}]*right:\s*0;/s);
  assert.match(css, /\.editor-resizer\s*\{[^}]*bottom:\s*var\(--app-editor-height\);/s);
  assert.match(css, /\.editor-resizer\s*\{[^}]*height:\s*12px;/s);
  assert.match(css, /\.editor-resizer\s*\{[^}]*cursor:\s*ns-resize;/s);
  assert.match(css, /\.editor-resizer::before\s*\{[^}]*height:\s*1px;/s);
  assert.match(css, /\.editor-resizer-grip\s*\{[^}]*width:\s*44px;/s);
  assert.match(css, /\.editor-resizer-grip\s*\{[^}]*height:\s*4px;/s);
  assert.match(css, /\.editor-resizer-grip\s*\{[^}]*border-radius:\s*999px;/s);
  assert.match(css, /\.editor-resizer:hover \.editor-resizer-grip,\s*\n\.app\.editor-resizing \.editor-resizer-grip\s*\{/s);
  assert.match(css, /\.app\.editor-resizing\s*\{[^}]*user-select:\s*none;/s);
  assert.match(css, /\.app\.editor-resizing \.editor-resizer\s*\{[^}]*cursor:\s*ns-resize;/s);
});

test('track list rows align with timeline hover rows', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /--track-row-size:\s*minmax\(clamp\(48px,\s*7\.5vh,\s*74px\),\s*1fr\);/);
  assert.match(css, /--track-footer-height:\s*48px;/);
  assert.match(css, /\.tracks-col\s*\{[^}]*grid-template-rows:\s*48px minmax\(0,\s*1fr\) var\(--track-footer-height\);/s);
  assert.match(css, /\.timeline-col\s*\{[^}]*grid-template-rows:\s*48px minmax\(0,\s*1fr\) var\(--track-footer-height\);/s);
  assert.match(css, /\.timeline-footer-spacer\s*\{[^}]*min-height:\s*var\(--track-footer-height\);/s);
  assert.match(css, /\.timeline-footer-spacer\s*\{[^}]*border-top:\s*1px solid var\(--border-soft\);/s);
  assert.match(css, /\.tracks-list\s*\{[^}]*grid-template-rows:\s*repeat\(var\(--track-count,\s*4\),\s*var\(--track-row-size\)\);/s);
  assert.match(css, /\.tracks-list\s*\{[^}]*overflow:\s*auto;/s);
  assert.match(css, /\.grid-rows,\s*\n\.hover-rows\s*\{[^}]*grid-template-rows:\s*repeat\(var\(--track-count,\s*4\),\s*var\(--track-row-size\)\);/s);
  assert.match(css, /\.hover-row\s*\{[^}]*position:\s*relative;/s);
  assert.doesNotMatch(css, /\.hover-row\s*\{[^}]*height:\s*var\(--timeline-clip-y-inset\);/s);
  assert.doesNotMatch(css, /\.hover-row\s*\{[^}]*top:\s*var\(--timeline-clip-y-inset\);/s);
  assert.doesNotMatch(css, /\.hover-row\s*\{[^}]*bottom:\s*var\(--timeline-clip-y-inset\);/s);
  assert.match(css, /\.add-track\s*\{[^}]*position:\s*static;/s);
  assert.doesNotMatch(css, /\.add-track\s*\{[^}]*position:\s*absolute;/s);
  assert.doesNotMatch(css, /\.add-track\s*\{[^}]*bottom:/s);
  assert.match(css, /\.add-track-row\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.add-track-menu\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.add-track-menu\s*\{[^}]*bottom:\s*calc\(100% - 4px\);/s);
  assert.doesNotMatch(css, /min-height:\s*74px;/);
});

test('timeline clips and add controls inherit the left track color map', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  for (const trackId of TRACK_IDS) {
    assert.match(css, new RegExp(`\\[data-type="${trackId}"\\]\\s*\\{[^}]*--track-color:\\s*var\\(--c-${trackId}\\);`, 's'));
    assert.match(css, new RegExp(`\\[data-type="${trackId}"\\]\\s*\\{[^}]*--track-ink:\\s*var\\(--c-${trackId}-ink\\);`, 's'));
  }

  assert.match(css, /\.clip\s*\{[^}]*--clip-bg:\s*var\(--track-color,\s*var\(--c-drums\)\);/s);
  assert.match(css, /\.clip\s*\{[^}]*--clip-ink:\s*var\(--track-ink,\s*var\(--c-drums-ink\)\);/s);
  assert.match(css, /\.add-clip\s*\{[^}]*color:\s*var\(--track-ink,\s*var\(--ink-3\)\);/s);
  assert.match(css, /\.add-clip\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--track-color,\s*var\(--surface\)\)/s);
});

test('track fill-empty clip button is compact and inherits track color', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.track-main-row\s*\{[^}]*grid-template-columns:\s*minmax\(76px,\s*1fr\) minmax\(0,\s*auto\);/s);
  assert.match(css, /\.track-select\s*\{[^}]*grid-template-columns:\s*38px minmax\(0,\s*1fr\);/s);
  assert.match(css, /\.track-select\s*\{[^}]*min-width:\s*76px;/s);
  assert.match(css, /\.ic\s*\{[^}]*min-width:\s*32px;/s);
  assert.match(css, /\.ic\s*\{[^}]*flex:\s*0 0 32px;/s);
  assert.match(css, /\.fill-empty-clips\s*\{[^}]*height:\s*28px;/s);
  assert.match(css, /\.fill-empty-clips\s*\{[^}]*min-width:\s*0;/s);
  assert.match(css, /\.fill-empty-clips\s*\{[^}]*max-width:\s*96px;/s);
  assert.match(css, /\.fill-empty-clips\s*\{[^}]*color:\s*var\(--track-ink,\s*var\(--ink-3\)\);/s);
  assert.match(css, /\.fill-empty-clips\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--track-color,\s*var\(--surface\)\)/s);
  assert.match(css, /\.fill-empty-clips-label\s*\{[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.fill-empty-clips-label\s*\{[^}]*text-overflow:\s*ellipsis;/s);
  assert.match(css, /\.fill-empty-clips:hover:not\(:disabled\),\s*\n\.fill-empty-clips:focus-visible:not\(:disabled\)\s*\{/s);
  assert.match(css, /\.fill-empty-clips-icon\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*4px\);/s);
  assert.match(css, /\.fill-empty-clips-icon span\s*\{[^}]*background:\s*currentColor;/s);
});

test('timeline drag and swap feedback is visually prominent', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.clip\.clip-dragging\s*\{[^}]*transform:\s*translateY\(-3px\) scale\(1\.02\);/s);
  assert.match(css, /\.clip\.drop-move,\s*\n\.clip\.drop-swap\s*\{[^}]*animation:\s*clip-drop-pop 0\.48s ease-out;/s);
  assert.match(css, /\.bar-drop-zone\.drag-over\s*\{[^}]*box-shadow:\s*inset 0 0 0 2px/s);
  assert.match(css, /\.bar-drop-zone\.drop-move,\s*\n\.bar-drop-zone\.drop-swap\s*\{[^}]*animation:\s*bar-drop-pulse 0\.7s ease-out;/s);
  assert.match(css, /@keyframes clip-drop-pop/);
  assert.match(css, /@keyframes bar-drop-pulse/);
});

test('drum sequencer uses three fixed rows and sixteen stable step columns', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.drum-seq-body\s*\{[^}]*overflow:\s*auto;/s);
  assert.match(css, /\.track-editor-pager-shell\s*\{[^}]*grid-template-columns:\s*36px minmax\(0,\s*1fr\) 36px;/s);
  assert.match(css, /\.track-editor-pager-shell\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.drum-seq-body \.track-editor-pager-shell\s*\{[^}]*grid-template-columns:\s*36px minmax\(max-content,\s*980px\) 36px;/s);
  assert.match(css, /\.drum-step-numbers,\s*\n\.drum-row\s*\{[^}]*grid-template-columns:\s*118px minmax\(0,\s*1fr\);/s);
  assert.match(css, /\.drum-row\s*\{[^}]*grid-template-columns:\s*118px minmax\(0,\s*1fr\);/s);
  assert.match(css, /\.drum-step-groups\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*max-content\);/s);
  assert.match(css, /\.drum-step-groups\s*\{[^}]*--drum-step-group-gap:\s*clamp\(12px,\s*2\.4vw,\s*22px\);/s);
  assert.match(css, /\.drum-step-groups\s*\{[^}]*--drum-step-group-gap-half:\s*clamp\(6px,\s*1\.2vw,\s*11px\);/s);
  assert.match(css, /\.drum-step-groups\s*\{[^}]*column-gap:\s*var\(--drum-step-group-gap\);/s);
  assert.match(css, /\.drum-step-group\s*\{[^}]*--drum-step-gap:\s*5px;/s);
  assert.match(css, /\.drum-step-group\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(18px,\s*32px\)\);/s);
  assert.match(css, /\.drum-step-group\s*\{[^}]*gap:\s*var\(--drum-step-gap\);/s);
  assert.doesNotMatch(css, /\.drum-step(?:-number)?\.beat-end\s*\{[^}]*margin-right:/s);
  assert.match(css, /\.track-page-btn\s*\{[^}]*width:\s*36px;/s);
  assert.match(css, /\.track-page-btn\s*\{[^}]*height:\s*64px;/s);
  assert.match(css, /\.track-page-btn\s*\{[^}]*color:\s*var\(--track-ink,\s*var\(--c-drums-ink\)\);/s);
  assert.match(css, /\.track-page-btn:hover:not\(:disabled\)\s*\{[^}]*background:\s*var\(--track-ink,\s*var\(--c-drums-ink\)\);/s);
  assert.match(css, /\.track-page-btn:disabled\s*\{[^}]*opacity:\s*0\.32;/s);
  assert.doesNotMatch(css, /\.drum-page-btn\s*\{/);
  assert.match(css, /\.drum-step-number\s*\{[^}]*justify-content:\s*center;[^}]*height:\s*16px;/s);
  assert.match(css, /\.drum-step-number\.beat-end::after\s*\{[^}]*position:\s*absolute;[^}]*right:\s*calc\(-1 \* var\(--drum-step-group-gap-half\)\);[^}]*transform:\s*translateX\(50%\);/s);
  assert.match(css, /\.drum-step\.beat-end::after\s*\{[^}]*position:\s*absolute;[^}]*right:\s*calc\(-1 \* var\(--drum-step-group-gap-half\)\);[^}]*transform:\s*translateX\(50%\);/s);
  assert.match(css, /\.drum-step\.active\[data-instrument="kick"\]/);
  assert.match(css, /\.drum-step\.active\[data-instrument="snare"\]/);
  assert.match(css, /\.drum-step\.active\[data-instrument="hihat"\]/);
  assert.match(css, /@media\s*\(max-width:\s*980px\)\s*\{[\s\S]*\.drum-step-group\s*\{[^}]*--drum-step-gap:\s*4px;[^}]*gap:\s*var\(--drum-step-gap\);/s);
});

test('chord pitch rail rows align with chord grid rows', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /--chord-cell-grid-height:\s*220px;/);
  assert.match(css, /--chord-cell-gap:\s*3px;/);
  assert.match(css, /--chord-cell-padding:\s*6px;/);
  assert.match(css, /--pitch-rail-head-height:\s*var\(--chord-beat-head-height\);/);
  assert.match(css, /--pitch-row-hover:\s*var\(--c-chord\);/);
  assert.match(css, /--pitch-row-hover-ink:\s*var\(--c-chord-ink\);/);
  assert.match(css, /\.editor\s*\{[^}]*grid-template-rows:\s*auto minmax\(0,\s*1fr\);/s);
  assert.match(css, /\.editor-head\s*\{[^}]*min-height:\s*54px;/s);
  assert.match(css, /\.app:has\(\.editor\[data-screen-label="Chord Editor"\]:not\(\[data-picker="chord"\]\):not\(\[data-picker="groove"\]\)\)\s*\{[^}]*--app-editor-height:\s*clamp\(360px,\s*46vh,\s*430px\);/s);
  assert.match(css, /\.scale-rail\s*\{[^}]*grid-template-rows:\s*var\(--pitch-rail-head-height\) var\(--chord-cell-grid-height\) 22px;/s);
  assert.match(css, /\.scale-rail\s*\{[^}]*gap:\s*var\(--chord-beat-gap\);/s);
  assert.match(css, /\.pitch-grid-head-spacer\s*\{[^}]*height:\s*var\(--pitch-rail-head-height\);/s);
  assert.match(css, /\.pitch-grid-head-spacer\s*\{[^}]*flex:\s*0 0 var\(--pitch-rail-head-height\);/s);
  assert.doesNotMatch(css, /\.pitch-grid-head-spacer\s*\{[^}]*(?:margin|transform|position):/s);
  assert.match(css, /\.scale-notes-viewport\s*\{[^}]*height:\s*var\(--chord-cell-grid-height\);/s);
  assert.match(css, /\.scale-notes-viewport\s*\{[^}]*overflow-y:\s*auto;/s);
  assert.match(css, /\.scale-notes\s*\{[^}]*grid-template-rows:\s*repeat\(36,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.scale-notes\s*\{[^}]*min-height:\s*calc\(var\(--chord-cell-grid-height\) \* 3\);/s);
  assert.match(css, /\.scale-notes\s*\{[^}]*gap:\s*var\(--chord-cell-gap\);/s);
  assert.match(css, /\.scale-notes\s*\{[^}]*padding:\s*var\(--chord-cell-padding\);/s);
  assert.match(css, /\.note-key\s*\{[^}]*min-height:\s*0;/s);
  assert.match(css, /\.beat-cells-viewport\s*\{[^}]*height:\s*var\(--chord-cell-grid-height\);/s);
  assert.match(css, /\.beat-cells-viewport\s*\{[^}]*overflow-y:\s*auto;/s);
  assert.match(css, /\.beat-cells\s*\{[^}]*grid-template-rows:\s*repeat\(36,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.beat-cells\s*\{[^}]*min-height:\s*calc\(var\(--chord-cell-grid-height\) \* 3\);/s);
  assert.match(css, /\.beat-cells\s*\{[^}]*gap:\s*var\(--chord-cell-gap\);/s);
  assert.match(css, /\.beat-cells\s*\{[^}]*padding:\s*var\(--chord-cell-padding\);/s);
  assert.doesNotMatch(css, /\.cell\.sustain/);
  assert.match(css, /\.chord-grid\s*\{[^}]*overflow-x:\s*auto;[^}]*overflow-y:\s*hidden;/s);
  assert.match(css, /\.chord-grid\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(128px,\s*1fr\)\);/s);
  assert.match(css, /\.beat-head\s*\{[^}]*display:\s*flex;[^}]*justify-content:\s*flex-start;/s);
  assert.match(css, /\.beat-head\s*\{[^}]*min-height:\s*var\(--chord-beat-head-height\);/s);
  assert.doesNotMatch(css, /\.chord-label-row\s*\{/);
  assert.doesNotMatch(css, /\.beat-number-row\s*\{/);
  assert.doesNotMatch(css, /\.beat-num\s*\{/);
  assert.match(css, /\.cell\.added,\s*\.cell\.active\.added\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--c-chord\) 35%,\s*white\);/s);
  assert.match(css, /\.note-key\.row-hovered\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--pitch-row-hover\)/s);
  assert.match(css, /\.cell\.row-hovered,\s*\n\.melody-cell\.row-hovered,\s*\n\.bass-cell\.row-hovered\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*var\(--pitch-row-hover-ink\)/s);
  assert.match(css, /\.cell\.row-hovered:not\(\.active\):not\(\.added\),\s*\n\.melody-cell\.row-hovered:not\(\.active\),\s*\n\.bass-cell\.row-hovered:not\(\.active\)\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--pitch-row-hover\)/s);
  assert.doesNotMatch(css, /\.cell\.active\.added\s*\{[^}]*linear-gradient/s);
  assert.doesNotMatch(css, /--chord-extension:/);
  assert.doesNotMatch(css, /--chord-extension-ink:/);
  assert.doesNotMatch(css, /\.cell\.extension/);
});

test('melody editor mirrors the reference keyboard strip and scale picker layout', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.app:has\(\.editor\[data-screen-label="Melody Editor"\]:not\(\[data-picker="scale"\]\)\)\s*\{[^}]*--app-editor-height:\s*clamp\(360px,\s*46vh,\s*430px\);/s);
  assert.match(css, /\.app:has\(\.editor\[data-picker="scale"\]\)\s*\{[^}]*--app-editor-height:\s*clamp\(380px,\s*55vh,\s*560px\);/s);
  assert.match(css, /\.editor\[data-screen-label="Melody Editor"\]\s*\{[^}]*grid-template-rows:\s*auto minmax\(0,\s*1fr\);/s);
  assert.match(css, /\.melody-editor-pager-shell\s*\{[^}]*align-items:\s*stretch;[^}]*min-height:\s*0;/s);
  assert.match(css, /\.melody-editor-pager-shell \.track-page-btn\s*\{[^}]*align-self:\s*center;/s);
  assert.match(css, /\.melody-editor-scroll\s*\{[^}]*min-height:\s*0;[^}]*overflow-y:\s*auto;[^}]*overscroll-behavior:\s*contain;[^}]*scrollbar-gutter:\s*stable;/s);
  assert.match(css, /\.melody-editor-scroll > \.keyboard-strip,\s*\n\.melody-editor-scroll > \.melody-example-keys,\s*\n\.melody-editor-scroll > \.melody-seq-body\s*\{[^}]*flex:\s*0 0 auto;/s);
  assert.match(css, /\.editor\[data-screen-label="Melody Editor"\] \.clip-chip\s*\{[^}]*background:\s*var\(--c-melody\);/s);
  assert.match(css, /\.keyboard-strip\s*\{[^}]*display:\s*flex;/s);
  assert.match(css, /\.ks-keys\s*\{[^}]*grid-template-columns:\s*repeat\(13,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.ks-key\.playing\s*\{[^}]*background:\s*var\(--c-melody\);/s);
  assert.match(css, /\.melody-grid\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(128px,\s*1fr\)\);/s);
  assert.match(css, /\.melody-seq-body\s*\{[^}]*--pitch-rail-head-height:\s*22px;/s);
  assert.match(css, /\.melody-seq-body\s*\{[^}]*--pitch-row-hover:\s*var\(--c-melody\);/s);
  assert.match(css, /\.melody-seq-body\s*\{[^}]*--pitch-row-hover-ink:\s*var\(--c-melody-ink\);/s);
  assert.match(css, /\.melody-seq-body\s*\{[^}]*--melody-pitch-row-count:\s*13;/s);
  assert.match(css, /\.melody-seq-body\s*\{[^}]*--melody-pitch-viewport-height:\s*var\(--chord-cell-grid-height\);/s);
  assert.doesNotMatch(css, /--melody-rail-row-count/);
  assert.doesNotMatch(css, /\.melody-scale-notes\s*\{[^}]*repeat\(var\(--melody-rail-row-count\)/s);
  assert.doesNotMatch(css, /\.melody-beat-cells\s*\{[^}]*repeat\(var\(--melody-rail-row-count\)/s);
  assert.doesNotMatch(css, /--melody-rail-row-total/);
  assert.match(css, /\.melody-seq-body \.scale-notes-viewport,\s*\n\.melody-seq-body \.beat-cells-viewport\s*\{[^}]*height:\s*var\(--melody-pitch-viewport-height\);[^}]*overflow-y:\s*hidden;/s);
  assert.match(css, /\.melody-scale-notes,\s*\n\.melody-beat-cells\s*\{[^}]*grid-template-rows:\s*repeat\(var\(--melody-pitch-row-count\),\s*minmax\(0,\s*1fr\)\);[^}]*gap:\s*var\(--chord-cell-gap\);[^}]*height:\s*var\(--melody-pitch-viewport-height\);[^}]*min-height:\s*var\(--melody-pitch-viewport-height\);[^}]*padding:\s*var\(--chord-cell-padding\);/s);
  assert.doesNotMatch(css, /\.melody-scale-notes\s*\{[^}]*min-height:\s*calc\(var\(--chord-cell-grid-height\) \* 3\);/s);
  assert.doesNotMatch(css, /\.melody-beat-cells\s*\{[^}]*min-height:\s*calc\(var\(--chord-cell-grid-height\) \* 3\);/s);
  assert.match(css, /\.melody-scale-rail\s*\{[^}]*grid-template-rows:\s*var\(--pitch-rail-head-height\) var\(--melody-pitch-viewport-height\) 22px;/s);
  assert.match(css, /\.melody-beat-group\s*\{[^}]*display:\s*flex;[^}]*flex-direction:\s*column;[^}]*gap:\s*var\(--chord-beat-gap\);/s);
  assert.doesNotMatch(css, /\.melody-beat-number-row\s*\{/);
  assert.doesNotMatch(css, /\.melody-cell\s*\{[^}]*background:\s*oklch\(97% 0\.003 270\);/s);
  assert.doesNotMatch(css, /\.melody-cell\.sharp\s*\{/);
  assert.doesNotMatch(css, /\.melody-cell:hover\s*\{/);
  assert.doesNotMatch(css, /\.melody-cell\.downbeat\s*\{/);
  assert.match(css, /\.melody-cell\.active\s*\{[^}]*background:\s*var\(--c-melody\);/s);
  assert.match(css, /\.melody-note-key\.playing\s*\{[^}]*background:\s*var\(--c-melody\)/s);
  assert.match(css, /\.scale-picker\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.app-main:has\(\.tutorial-panel\) \.scale-picker:has\(\.sctpl-card\.tutorial-control-target\)\s*\{[^}]*z-index:\s*calc\(var\(--tutorial-target-z\) \+ 1\);/s);
  assert.match(css, /\.sctpl-card\.selected\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--c-melody\) 20%,\s*var\(--surface\)\);/s);
  assert.match(css, /\.sctpl-card\.tutorial-control-target\s*\{[^}]*background:\s*var\(--tutorial-target-surface\);[^}]*border-color:\s*var\(--tutorial-target-rim\);/s);
  assert.match(css, /\.sctpl-card\.tutorial-control-target\s*\{[^}]*z-index:\s*calc\(var\(--tutorial-target-z\) \+ 2\);/s);
  assert.match(css, /\.sctpl-card\.tutorial-control-target \.sctpl-notes\s*\{[^}]*background:\s*color-mix\(in oklab,\s*white 78%,\s*var\(--c-melody\)\);/s);
  assert.match(css, /\.sctpl-card\.tutorial-control-target \.sctpl-note:not\(\.gap\)\s*\{[^}]*background:\s*color-mix\(in oklab,\s*white 86%,\s*var\(--c-melody\)\);/s);
  assert.match(css, /\.scale-picker:has\(\.sctpl-card\.tutorial-control-target\) \.sctpl-card:not\(\.tutorial-control-target\)\s*\{[^}]*opacity:\s*0\.44;/s);
  assert.match(css, /\.melody-example-keys\.tutorial-control-target\s*\{[^}]*background:\s*var\(--tutorial-target-surface\);[^}]*border-color:\s*var\(--tutorial-target-rim\);/s);
  assert.match(css, /\.melody-example-key\s*\{[^}]*display:\s*inline-flex;/s);
});

test('bass editor mirrors the reference piano-roll and groove picker layout', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.app:has\(\.editor\[data-screen-label="Bass Editor"\]:not\(\[data-picker="groove"\]\)\)\s*\{[^}]*--app-editor-height:\s*clamp\(360px,\s*46vh,\s*430px\);/s);
  assert.match(css, /\.editor\[data-screen-label="Bass Editor"\] \.clip-chip\s*\{[^}]*background:\s*var\(--c-bass\);/s);
  assert.match(css, /\.scale-notes\s*\{[^}]*grid-template-rows:\s*repeat\(36,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.beat-cells\s*\{[^}]*grid-template-rows:\s*repeat\(36,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.bass-seq-body\s*\{[^}]*--pitch-rail-head-height:\s*22px;/s);
  assert.match(css, /\.bass-seq-body\s*\{[^}]*--pitch-row-hover:\s*var\(--c-bass\);/s);
  assert.match(css, /\.bass-seq-body\s*\{[^}]*--pitch-row-hover-ink:\s*var\(--c-bass-ink\);/s);
  assert.doesNotMatch(css, /\.bass-beat-number-row\s*\{/);
  assert.doesNotMatch(css, /\.bass-scale-notes\s*\{[^}]*grid-template-rows:\s*repeat\(12,/s);
  assert.doesNotMatch(css, /\.bass-beat-cells\s*\{[^}]*grid-template-rows:\s*repeat\(12,/s);
  assert.match(css, /\.bass-note-key\.root\s*\{[^}]*color:\s*var\(--c-bass-ink\);/s);
  assert.match(css, /\.bass-note-key:hover\s*\{[^}]*background:\s*var\(--c-bass\);/s);
  assert.match(css, /\.bass-cell\.active\s*\{[^}]*background:\s*var\(--c-bass\);/s);
  assert.match(css, /\.bass-cell:hover\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--c-bass\) 60%,\s*white\);/s);
  assert.match(css, /\.gtpl-step\.hit-root\s*\{[^}]*overflow:\s*visible;/s);
  assert.match(css, /\.gtpl-step\.hit-root::after\s*\{[^}]*bottom:\s*14%;/s);
  assert.match(css, /\.gtpl-step\.hit-root::after\s*\{[^}]*height:\s*32%;/s);
  assert.match(css, /\.gtpl-step\.hit-root\[data-len="8"\]::after\s*\{[^}]*width:\s*calc\(188% \+ 2px\);/s);
});

test('chord template picker has enough room and can scroll full card content', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.app:has\(\.editor\[data-picker="chord"\]\),\s*\n\.app:has\(\.editor\[data-picker="groove"\]\)\s*\{[^}]*--app-editor-height:\s*clamp\(380px,\s*55vh,\s*560px\);/s);
  assert.match(css, /\.tpl-body\s*\{[^}]*overflow:\s*auto;/s);
  assert.match(css, /\.tpl-list\s*\{[^}]*height:\s*auto;/s);
  assert.match(css, /\.tpl-list\s*\{[^}]*min-height:\s*100%;/s);
  assert.match(css, /\.tpl-confirm-overlay\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.tpl-confirm-overlay\s*\{[^}]*inset:\s*0;/s);
  assert.match(css, /\.tpl-confirm-dialog\s*\{[^}]*display:\s*grid;/s);
  assert.match(css, /\.tpl-confirm-actions\s*\{[^}]*display:\s*flex;/s);
  assert.match(css, /\.tpl-confirm-cancel\s*\{[^}]*background:\s*var\(--surface\);/s);
  assert.match(css, /\.tpl-confirm-apply\s*\{[^}]*background:\s*var\(--ink\);/s);
  assert.doesNotMatch(css, /\.tpl-body\s*\{[^}]*overflow:\s*hidden;/s);
});

test('groove template picker mirrors the reference secondary menu layout', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.btn-template-groove\s*\{[^}]*display:\s*inline-flex;/s);
  assert.match(css, /\.btn-template-groove-active\s*\{[^}]*display:\s*inline-flex;/s);
  assert.match(css, /\.btn-template-groove-active\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.btn-template-groove-active\s*\{[^}]*justify-content:\s*center;/s);
  assert.match(css, /\.gtpl-picker\s*\{[^}]*grid-template-rows:\s*48px 1fr 52px;/s);
  assert.match(css, /\.tpl-picker\s*\{[^}]*z-index:\s*8;/s);
  assert.match(css, /\.gtpl-picker\s*\{[^}]*z-index:\s*8;/s);
  assert.match(css, /\.app-main:has\(\.tutorial-panel\) \.tpl-picker:not\(\[hidden\]\),\s*\n\.app-main:has\(\.tutorial-panel\) \.gtpl-picker:not\(\[hidden\]\)\s*\{[^}]*z-index:\s*var\(--tutorial-floating-ui-z\);/s);
  assert.match(css, /\.gtpl-list-centered\s*\{[^}]*grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.gtpl-list-centered\s*\{[^}]*justify-content:\s*center;/s);
  assert.match(css, /\.gtpl-list-centered > \.gtpl-card\s*\{[^}]*grid-column:\s*span 2;/s);
  assert.match(css, /\.gtpl-list-centered > \.gtpl-card:first-child\s*\{[^}]*grid-column:\s*2 \/ span 2;/s);
  assert.match(css, /@media \(max-width:\s*760px\)\s*\{[\s\S]*\.gtpl-list-centered\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\);[\s\S]*\.gtpl-list-centered > \.gtpl-card\s*\{[^}]*grid-column:\s*auto;/s);
  assert.match(css, /\.gtpl-card\s*\{[^}]*display:\s*flex;/s);
  assert.match(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*--tutorial-highlight-rest-shadow:\s*var\(--tutorial-target-contained-rest-shadow\);/s);
  assert.match(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*background:\s*color-mix\(in oklab,\s*white 78%,\s*var\(--tutorial-target-surface\)\);/s);
  assert.match(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*border:\s*1px solid var\(--tutorial-target-surface-border\);/s);
  assert.match(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*outline-offset:\s*-4px;/s);
  assert.match(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*opacity:\s*1;/s);
  assert.doesNotMatch(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*grid-column:/s);
  assert.doesNotMatch(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*width:/s);
  assert.doesNotMatch(css, /\.tpl-card\.tutorial-control-target,\s*\n\.gtpl-card\.tutorial-control-target\s*\{[^}]*height:/s);
  assert.match(css, /\.gtpl-rhythm-grid\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*1fr\);/s);
  assert.match(css, /\.gtpl-beat\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*1fr\);/s);
  assert.match(css, /\.gtpl-step\.hit-block::after\s*\{/s);
  assert.match(css, /\.gtpl-step\.hit-arp::after\s*\{[^}]*height:\s*calc\(28% \+ var\(--h,\s*1\) \* 18%\);/s);
  assert.match(css, /\.gtpl-picker \.tpl-pager-btn:hover:not\(:disabled\)\s*\{[^}]*background:\s*var\(--ink\);/s);
});

test('active chord template button aligns icon and label on one baseline', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.btn-template-active\s*\{[^}]*display:\s*inline-flex;/s);
  assert.match(css, /\.btn-template-active\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.btn-template-active\s*\{[^}]*justify-content:\s*center;/s);
  assert.match(css, /\.btn-template-active\s*\{[^}]*line-height:\s*1;/s);
  assert.match(css, /\.btn-template-active svg\s*\{[^}]*width:\s*14px;/s);
  assert.match(css, /\.btn-template-active svg\s*\{[^}]*height:\s*14px;/s);
  assert.match(css, /\.btn-template-active svg\s*\{[^}]*flex:\s*0 0 auto;/s);
});

test('global history buttons keep independent toolbar sizing and disabled feedback', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.history-controls\s*\{[^}]*display:\s*flex;/s);
  assert.match(css, /\.history-controls\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.history-controls\s*\{[^}]*gap:\s*4px;/s);
  assert.match(css, /\.history-controls\s*\{[^}]*padding:\s*4px;/s);
  assert.match(css, /\.history-controls\s*\{[^}]*border-radius:\s*12px;/s);
  assert.match(css, /\.t-btn\.undo,\s*\.t-btn\.redo\s*\{[^}]*flex:\s*0 0 32px;/s);
  assert.match(css, /\.t-btn\.undo,\s*\.t-btn\.redo\s*\{[^}]*width:\s*32px;/s);
  assert.match(css, /\.t-btn\.undo,\s*\.t-btn\.redo\s*\{[^}]*height:\s*32px;/s);
  assert.match(css, /\.t-btn:disabled\s*\{[^}]*opacity:\s*0\.38;/s);
  assert.match(css, /\.t-btn:disabled\s*\{[^}]*cursor:\s*not-allowed;/s);
  assert.match(css, /\.t-btn:disabled:hover\s*\{[^}]*background:\s*transparent;/s);
  assert.match(css, /\.t-btn:disabled:hover\s*\{[^}]*box-shadow:\s*none;/s);
  assert.doesNotMatch(css, /@media \(max-width:\s*980px\)[\s\S]*\.history-controls\s*\{[^}]*display:\s*none;/);
  assert.doesNotMatch(css, /@media \(max-width:\s*980px\)[\s\S]*\.t-btn\.redo\s*\{[^}]*display:\s*none;/);
});

test('tutorial sidebar is embedded as a workbench column and reopens from the topbar', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.workspace\.tutorial-sidebar-open\s*\{[^}]*grid-template-columns:\s*clamp\(188px,\s*18vw,\s*246px\) minmax\(0,\s*1fr\) clamp\(300px,\s*24vw,\s*360px\);/s);
  assert.match(css, /\.workspace\.tutorial-sidebar-collapsed\s*\{[^}]*grid-template-columns:\s*clamp\(188px,\s*18vw,\s*246px\) minmax\(0,\s*1fr\);/s);
  assert.doesNotMatch(css, /\.app\.tutorial-sidebar-open\s*\{[^}]*grid-template-columns:/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*display:\s*inline-flex;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*justify-content:\s*center;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*width:\s*58px;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*height:\s*36px;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*flex:\s*0 0 58px;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*font-size:\s*13px;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*font-weight:\s*800;/s);
  assert.match(css, /\.tutorial-topbar-button\s*\{[^}]*white-space:\s*nowrap;/s);
  assert.match(css, /--tutorial-floating-ui-z:\s*110;/);
  assert.match(css, /@media \(max-width:\s*980px\)\s*\{[\s\S]*\.topbar-center\s*\{[^}]*grid-row:\s*2;/);
  assert.match(css, /@media \(max-width:\s*980px\)\s*\{[\s\S]*\.right-tools\s*\{[^}]*grid-column:\s*2;[^}]*grid-row:\s*1;/);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*z-index:\s*90;/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*grid-template-rows:\s*48px minmax\(0,\s*1fr\) var\(--track-footer-height\);/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*width:\s*100%;/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*height:\s*100%;/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*padding:\s*0;/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--surface\) 58%,\s*var\(--bg\)\);/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*border-left:\s*1px solid/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*border-radius:\s*0;/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*font-family:\s*"Baloo 2",\s*"Nunito",\s*"Arial Rounded MT Bold",\s*"Avenir Next Rounded",\s*"Trebuchet MS",\s*"PingFang SC",\s*"Microsoft YaHei",\s*sans-serif;/s);
  assert.match(css, /\.tutorial-panel\s*\{[^}]*text-align:\s*center;/s);
  assert.match(css, /\.tutorial-panel-header\s*\{[^}]*display:\s*flex;/s);
  assert.match(css, /\.tutorial-panel-header\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.tutorial-panel-header\s*\{[^}]*justify-content:\s*flex-start;/s);
  assert.match(css, /\.tutorial-panel-header\s*\{[^}]*min-height:\s*48px;/s);
  assert.match(css, /\.tutorial-panel-header\s*\{[^}]*border-bottom:\s*1px solid var\(--border-soft\);/s);
  assert.doesNotMatch(css, /\.tutorial-panel-header\s*\{[^}]*grid-template-rows:/s);
  assert.doesNotMatch(css, /\.tutorial-panel-header\s*\{[^}]*justify-content:\s*space-between;/s);
  assert.doesNotMatch(css, /\.tutorial-panel-tools/);
  assert.doesNotMatch(css, /\.tutorial-icon-button/);
  assert.doesNotMatch(css, /\.tutorial-panel-title-row/);
  assert.match(css, /\.tutorial-directory\s*\{[^}]*display:\s*flex;/s);
  assert.match(css, /\.tutorial-directory\s*\{[^}]*justify-content:\s*flex-end;/s);
  assert.doesNotMatch(css, /\.tutorial-directory\s*\{[^}]*grid-template-columns:/s);
  assert.doesNotMatch(css, /\.tutorial-directory\s*\{[^}]*padding:\s*0 12px 10px;/s);
  assert.doesNotMatch(css, /\.tutorial-directory\s*\{[^}]*margin:\s*0 auto 8px;/s);
  assert.match(css, /\.tutorial-directory-button\s*\{[^}]*min-height:\s*24px;/s);
  assert.match(css, /\.tutorial-directory-button\s*\{[^}]*font-size:\s*10\.5px;/s);
  assert.match(css, /\.tutorial-directory-button\s*\{[^}]*border-radius:\s*6px;/s);
  assert.doesNotMatch(css, /\.tutorial-directory-button\s*\{[^}]*border-radius:\s*999px;/s);
  assert.match(css, /\.tutorial-directory-button\.active\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--c-drums\) 26%,\s*white\);/s);
  assert.match(css, /\.tutorial-directory-button:disabled\s*\{[^}]*opacity:\s*0\.36;/s);
  assert.match(css, /\.tutorial-panel-body\s*\{[^}]*justify-items:\s*center;/s);
  assert.match(css, /\.tutorial-copy\s*\{[^}]*display:\s*grid;/s);
  assert.match(css, /\.tutorial-copy\s*\{[^}]*gap:\s*12px;/s);
  assert.match(css, /\.tutorial-copy-title\s*\{[^}]*font-size:\s*24px;/s);
  assert.match(css, /\.tutorial-copy-title\s*\{[^}]*font-weight:\s*900;/s);
  assert.match(css, /\.tutorial-copy-subtitle\s*\{[^}]*font-size:\s*18px;/s);
  assert.match(css, /\.tutorial-copy-subtitle\s*\{[^}]*color:\s*var\(--c-drums-ink\);/s);
  assert.match(css, /\.tutorial-copy-body\s*\{[^}]*font-size:\s*15px;/s);
  assert.match(css, /\.tutorial-copy-body\s*\{[^}]*font-weight:\s*650;/s);
  assert.match(css, /\.tutorial-copy-body\s*\{[^}]*line-height:\s*1\.62;/s);
  assert.match(css, /\.tutorial-copy-title,\s*\n\.tutorial-copy-subtitle,\s*\n\.tutorial-copy-body\s*\{[^}]*text-align:\s*center;/s);
  assert.match(css, /\.tutorial-copy-title,\s*\n\.tutorial-copy-subtitle,\s*\n\.tutorial-copy-body\s*\{[^}]*overflow-wrap:\s*anywhere;/s);
  assert.doesNotMatch(css, /\.tutorial-copy-action-hint/);
  assert.doesNotMatch(css, /\.tutorial-copy-line/);
  assert.doesNotMatch(css, /\.tutorial-copy-body\s*\{[^}]*font-weight:\s*800;/s);
  assert.doesNotMatch(css, /\.tutorial-panel p\s*\{/);
  assert.match(css, /\.tutorial-panel-actions\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.tutorial-panel-actions\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.tutorial-panel-actions\s*\{[^}]*gap:\s*6px;/s);
  assert.match(css, /\.tutorial-panel-actions\s*\{[^}]*height:\s*var\(--track-footer-height\);/s);
  assert.match(css, /\.tutorial-panel-actions\s*\{[^}]*min-height:\s*0;/s);
  assert.match(css, /\.tutorial-panel-actions\s*\{[^}]*padding:\s*5px 12px;/s);
  assert.match(css, /\.tutorial-panel-actions\s*\{[^}]*border-top:\s*1px solid var\(--border-soft\);/s);
  assert.match(css, /\.timeline-footer-spacer\s*\{[^}]*height:\s*var\(--track-footer-height\);/s);
  assert.match(css, /\.add-track-row\s*\{[^}]*height:\s*var\(--track-footer-height\);/s);
  assert.match(css, /\.tutorial-primary,\s*\n\.tutorial-secondary,\s*\n\.tutorial-link\s*\{[^}]*min-height:\s*36px;/s);
  assert.match(css, /\.tutorial-primary,\s*\n\.tutorial-secondary,\s*\n\.tutorial-link\s*\{[^}]*height:\s*36px;/s);
  assert.match(css, /\.tutorial-primary,\s*\n\.tutorial-secondary,\s*\n\.tutorial-link\s*\{[^}]*border-radius:\s*999px;/s);
  assert.match(css, /\.tutorial-primary,\s*\n\.tutorial-secondary,\s*\n\.tutorial-link\s*\{[^}]*font-size:\s*13px;/s);
  assert.doesNotMatch(css, /\.tutorial-panel\s*\{[^}]*height:\s*100dvh;/s);
  assert.doesNotMatch(css, /\.tutorial-panel\s*\{[^}]*backdrop-filter:/s);
  assert.doesNotMatch(css, /\.tutorial-panel\s*\{[^}]*-14px 0 36px/s);
  assert.doesNotMatch(css, /\.tutorial-panel-actions\s*\{[^}]*min-height:\s*var\(--track-footer-height\);/s);
  assert.doesNotMatch(css, /\.tutorial-panel-actions\s*\{[^}]*padding:\s*10px 12px;/s);
  assert.doesNotMatch(css, /\.tutorial-reopen-button/);
  assert.doesNotMatch(css, /\.tutorial-panel\[data-placement=/);
  assert.match(css, /--tutorial-breathe-duration:\s*1\.25s;/);
  assert.match(css, /--tutorial-breathe-ease:\s*cubic-bezier\(0\.37,\s*0,\s*0\.63,\s*1\);/);
  assert.match(css, /--tutorial-spotlight-z:\s*50;/);
  assert.match(css, /--tutorial-target-z:\s*60;/);
  assert.match(css, /\.tutorial-target-active\s*\{[^}]*--tutorial-highlight-accent:\s*var\(--c-drums\);/s);
  assert.match(css, /\.tutorial-target-active\s*\{[^}]*--tutorial-highlight-ink:\s*var\(--c-drums-ink\);/s);
  assert.match(css, /\.tutorial-target-active\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.tutorial-target-active\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*white 58%,\s*transparent\);/s);
  assert.match(css, /\.tutorial-target-active\s*\{[^}]*outline-offset:\s*3px;/s);
  assert.match(css, /\.tutorial-target-active\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.match(css, /\.tutorial-target-active\s*\{[^}]*animation:\s*tutorial-highlight-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.match(css, /--tutorial-highlight-rest-shadow:[\s\S]*0 0 0 2px color-mix\(in oklab,\s*white 42%,\s*transparent\)/s);
  assert.match(css, /--tutorial-highlight-rest-shadow:[\s\S]*var\(--tutorial-highlight-accent\) 18%,\s*transparent/s);
  assert.match(css, /--tutorial-highlight-peak-shadow:[\s\S]*0 0 0 2px color-mix\(in oklab,\s*white 52%,\s*transparent\)/s);
  assert.match(css, /--tutorial-highlight-peak-shadow:[\s\S]*var\(--tutorial-highlight-accent\) 24%,\s*transparent/s);
  assert.doesNotMatch(css, /--tutorial-highlight-peak-shadow:[\s\S]*white 90%/s);
  assert.doesNotMatch(css, /--tutorial-highlight-peak-shadow:[\s\S]*var\(--tutorial-highlight-accent\) 68%/s);
  assert.match(css, /--tutorial-target-surface:\s*color-mix\(in oklab,\s*var\(--surface\) 74%,\s*var\(--tutorial-highlight-accent\)\);/);
  assert.match(css, /--tutorial-target-ink:\s*var\(--tutorial-highlight-ink\);/);
  assert.match(css, /--tutorial-target-surface-border:\s*color-mix\(in oklab,\s*var\(--tutorial-highlight-ink\) 18%,\s*transparent\);/);
  assert.match(css, /--tutorial-target-contained-rest-shadow:[\s\S]*inset 0 0 0 2px color-mix\(in oklab,\s*white 52%,\s*transparent\)/s);
  assert.match(css, /--tutorial-target-contained-peak-shadow:[\s\S]*inset 0 0 0 2px color-mix\(in oklab,\s*white 60%,\s*transparent\)/s);
  assert.match(css, /\.app-main:has\(\.tutorial-target-active\)::before,\s*\n\.app-main:has\(\.tutorial-bar-target\)::before,\s*\n\.app-main:has\(\.tutorial-control-target\)::before,\s*\n\.app-main:has\(\.tutorial-cell-target\)::before,\s*\n\.app-main:has\(\.tutorial-cell-source\)::before,\s*\n\.app-main:has\(\.tutorial-playhead-target\)::before\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.app-main:has\(\.tutorial-target-active\)::before,\s*\n\.app-main:has\(\.tutorial-bar-target\)::before,\s*\n\.app-main:has\(\.tutorial-control-target\)::before,\s*\n\.app-main:has\(\.tutorial-cell-target\)::before,\s*\n\.app-main:has\(\.tutorial-cell-source\)::before,\s*\n\.app-main:has\(\.tutorial-playhead-target\)::before\s*\{[^}]*background:\s*color-mix\(in oklab,\s*black 46%,\s*transparent\);/s);
  assert.match(css, /\.app-main:has\(\.tutorial-target-active\)::before,\s*\n\.app-main:has\(\.tutorial-bar-target\)::before,\s*\n\.app-main:has\(\.tutorial-control-target\)::before,\s*\n\.app-main:has\(\.tutorial-cell-target\)::before,\s*\n\.app-main:has\(\.tutorial-cell-source\)::before,\s*\n\.app-main:has\(\.tutorial-playhead-target\)::before\s*\{[^}]*z-index:\s*var\(--tutorial-spotlight-z\);/s);
  assert.doesNotMatch(css, /black 34%,\s*transparent/);
  assert.match(css, /\.topbar:has\(\.tutorial-transport-target\)\s*\{[^}]*z-index:\s*calc\(var\(--tutorial-target-z\) \+ 2\);/s);
  assert.match(css, /\.topbar:has\(\.tutorial-transport-target\)::after\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.topbar:has\(\.tutorial-transport-target\)::after\s*\{[^}]*z-index:\s*1;/s);
  assert.match(css, /\.topbar:has\(\.tutorial-transport-target\)::after\s*\{[^}]*background:\s*color-mix\(in oklab,\s*black 46%,\s*transparent\);/s);
  assert.match(css, /\.tutorial-target-active::after\s*\{[^}]*content:\s*"当前步骤";/s);
  assert.match(css, /\.tutorial-target-active::after\s*\{[^}]*font-size:\s*13px;/s);
  assert.match(css, /\.tutorial-panel-header::before\s*\{[^}]*content:\s*"";/s);
  assert.match(css, /\.tutorial-panel-header::before\s*\{[^}]*width:\s*3px;/s);
  assert.match(css, /\.tutorial-panel-header::before\s*\{[^}]*height:\s*18px;/s);
  assert.match(css, /\.tutorial-panel-header::before\s*\{[^}]*box-shadow:\s*none;/s);
  assert.match(css, /\.tutorial-panel-header::before\s*\{[^}]*animation:\s*tutorial-panel-rail-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.match(css, /@keyframes tutorial-panel-rail-breathe/);
  assert.doesNotMatch(css, /@keyframes tutorial-panel-step-breathe/);
  assert.match(css, /@keyframes tutorial-highlight-breathe/);
  assert.match(css, /50%\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-peak-shadow\);/s);
  assert.doesNotMatch(css, /@keyframes tutorial-target-pulse/);
});

test('tutorial task targets make allowed cells and bars obvious', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*animation:\s*tutorial-highlight-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*white 60%,\s*transparent\);/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*outline-offset:\s*2px;/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*--tutorial-cell-surface:\s*color-mix\(in oklab,\s*white 46%,\s*var\(--tutorial-cell-accent\)\);/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*--tutorial-cell-border:\s*color-mix\(in oklab,\s*var\(--tutorial-cell-accent\) 82%,\s*var\(--tutorial-cell-ink\)\);/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*background:\s*var\(--tutorial-cell-surface\);/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*border-color:\s*var\(--tutorial-cell-border\);/s);
  assert.match(css, /\.tutorial-cell-target\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.match(css, /\.drum-step\.active\.tutorial-cell-target\s*\{[^}]*background:\s*var\(--tutorial-cell-surface\);/s);
  assert.match(css, /\.drum-step\.active\.tutorial-cell-target\s*\{[^}]*border-color:\s*var\(--tutorial-cell-border\);/s);
  assert.doesNotMatch(css, /@keyframes tutorial-cell-pulse/);
  assert.doesNotMatch(css, /transform:\s*scale\(1\.13\);/);
  assert.match(css, /\.tutorial-cell-target-blue\s*\{[^}]*--tutorial-cell-accent:\s*oklch\(70% 0\.17 252\);/s);
  assert.match(css, /\.tutorial-cell-target-blue\s*\{[^}]*--tutorial-cell-ink:\s*oklch\(36% 0\.14 252\);/s);
  assert.match(css, /\.tutorial-cell-target-green\s*\{[^}]*--tutorial-cell-accent:\s*oklch\(72% 0\.16 150\);/s);
  assert.match(css, /\.tutorial-cell-target-green\s*\{[^}]*--tutorial-cell-ink:\s*oklch\(35% 0\.13 150\);/s);
  assert.match(css, /\.tutorial-cell-target-yellow\s*\{[^}]*--tutorial-cell-accent:\s*oklch\(84% 0\.18 88\);/s);
  assert.match(css, /\.tutorial-cell-target-yellow\s*\{[^}]*--tutorial-cell-ink:\s*oklch\(42% 0\.13 82\);/s);
  assert.doesNotMatch(css, /--tutorial-cell-accent:\s*#3b82f6;/);
  assert.doesNotMatch(css, /--tutorial-cell-accent:\s*#22c55e;/);
  assert.doesNotMatch(css, /--tutorial-cell-accent:\s*#facc15;/);
  assert.doesNotMatch(css, /\.tutorial-cell-target-blue\s*\{[^}]*animation:/s);
  assert.doesNotMatch(css, /\.tutorial-cell-target-green\s*\{[^}]*animation:/s);
  assert.doesNotMatch(css, /\.tutorial-cell-target-yellow\s*\{[^}]*animation:/s);
  assert.doesNotMatch(css, /\.tutorial-cell-existing/);
  assert.doesNotMatch(css, /\.tutorial-cell-completed/);
  assert.match(css, /\.drum-step\.active\[data-instrument="kick"\]\s*\{[^}]*background:\s*var\(--drum-kick\);/s);
  assert.match(css, /\.drum-step\.active\[data-instrument="kick"\]\s*\{[^}]*border-color:\s*color-mix\(in oklab,\s*var\(--drum-kick\) 70%,\s*black\);/s);
  assert.match(css, /\.tutorial-cell-source\s*\{[^}]*cursor:\s*grab;/s);
  assert.match(css, /\.tutorial-cell-source\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.tutorial-cell-source\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.tutorial-cell-source\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*white 60%,\s*transparent\);/s);
  assert.match(css, /\.tutorial-cell-source\s*\{[^}]*animation:\s*tutorial-highlight-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.match(css, /\.drum-step\.tutorial-cell-source::before\s*\{[^}]*pointer-events:\s*none;[^}]*animation:\s*tutorial-kick-drag-ghost 2\.4s cubic-bezier\(0\.37,\s*0,\s*0\.24,\s*1\) infinite;/s);
  assert.match(css, /@keyframes tutorial-kick-drag-ghost\s*\{[\s\S]*transform:\s*translateX\(calc\(\(100% \+ var\(--drum-step-gap\)\) \* 2\)\) scale\(1\.08\);/s);
  assert.match(css, /\.drum-step\.tutorial-locked:not\(\.active\):not\(\.tutorial-cell-target\):not\(\.tutorial-cell-source\)\s*\{[^}]*opacity:\s*0\.18;/s);
  assert.match(css, /\.drum-step\.tutorial-locked:not\(\.active\):not\(\.tutorial-cell-target\):not\(\.tutorial-cell-source\)\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--surface\) 45%,\s*var\(--ink-4\)\);/s);
  assert.match(css, /\.drum-step\.tutorial-locked:not\(\.active\):not\(\.tutorial-cell-target\):not\(\.tutorial-cell-source\)\s*\{[^}]*border-color:\s*color-mix\(in oklab,\s*var\(--border\) 42%,\s*var\(--ink-4\)\);/s);
  assert.match(css, /\.drum-step\.tutorial-locked:not\(\.active\):not\(\.tutorial-cell-target\):not\(\.tutorial-cell-source\)\s*\{[^}]*filter:\s*grayscale\(1\) saturate\(0\.2\);/s);
  assert.match(css, /\.drum-step\.tutorial-locked:not\(\.active\):not\(\.tutorial-cell-target\):not\(\.tutorial-cell-source\)\s*\{[^}]*transform:\s*none;/s);
  assert.doesNotMatch(css, /\.drum-step\.tutorial-locked:not\(\.tutorial-cell-target\):not\(\.tutorial-cell-source\)\s*\{[^}]*opacity:\s*0\.18;/s);
  assert.match(css, /\.tutorial-bar-target\s*\{[^}]*animation:\s*tutorial-highlight-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.match(css, /\.tutorial-bar-target\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.tutorial-bar-target\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.tutorial-bar-target\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*white 58%,\s*transparent\);/s);
  assert.match(css, /\.tutorial-bar-target\s*\{[^}]*outline-offset:\s*3px;/s);
  assert.match(css, /\.tutorial-bar-target\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.doesNotMatch(css, /\.tutorial-bar-target\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--tutorial-highlight-accent\) 14%,\s*transparent\);/s);
  assert.match(css, /\.fill-empty-clips\.tutorial-control-target,\s*\n\.clip\.tutorial-bar-target\s*\{[^}]*color:\s*var\(--tutorial-target-ink\);/s);
  assert.match(css, /\.fill-empty-clips\.tutorial-control-target,\s*\n\.clip\.tutorial-bar-target\s*\{[^}]*background:\s*var\(--tutorial-target-surface\);/s);
  assert.match(css, /\.fill-empty-clips\.tutorial-control-target,\s*\n\.clip\.tutorial-bar-target\s*\{[^}]*border:\s*1px solid var\(--tutorial-target-surface-border\);/s);
  assert.match(css, /\.clip\.tutorial-bar-target\s*\{[^}]*--clip-bg:\s*var\(--tutorial-target-surface\);/s);
  assert.match(css, /\.clip\.tutorial-bar-target\s*\{[^}]*--clip-ink:\s*var\(--tutorial-target-ink\);/s);
  assert.match(css, /\.clip\.tutorial-bar-target\s*\{[^}]*--tutorial-highlight-rest-shadow:\s*var\(--tutorial-target-contained-rest-shadow\);/s);
  assert.match(css, /\.clip\.tutorial-bar-target\s*\{[^}]*--tutorial-highlight-peak-shadow:\s*var\(--tutorial-target-contained-peak-shadow\);/s);
  assert.match(css, /\.clip\.tutorial-bar-target\s*\{[^}]*position:\s*absolute;/s);
  assert.match(css, /\.clip\.tutorial-bar-target\s*\{[^}]*outline-offset:\s*-3px;/s);
  assert.doesNotMatch(css, /\.clip\.tutorial-bar-target\s*\{[^}]*top:/s);
  assert.doesNotMatch(css, /\.clip\.tutorial-bar-target\s*\{[^}]*bottom:/s);
  assert.doesNotMatch(css, /\.clip\.tutorial-bar-target\s*\{[^}]*height:/s);
  assert.match(css, /\.tutorial-bar-completed\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-complete-shadow\);/s);
  assert.doesNotMatch(css, /@keyframes tutorial-bar-pulse/);
  assert.doesNotMatch(css, /transform:\s*scaleX\(1\.015\);/);
  assert.match(css, /\.tutorial-control-target\s*\{[^}]*animation:\s*tutorial-highlight-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.match(css, /\.tutorial-control-target\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.tutorial-control-target\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.tutorial-control-target\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*white 58%,\s*transparent\);/s);
  assert.match(css, /\.tutorial-control-target\s*\{[^}]*outline-offset:\s*3px;/s);
  assert.match(css, /\.tutorial-control-target\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.doesNotMatch(css, /\.tutorial-control-target\s*\{[^}]*transform:/s);
  assert.doesNotMatch(css, /@keyframes tutorial-control-pulse/);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*--tutorial-highlight-accent:\s*var\(--c-drums\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*--tutorial-highlight-ink:\s*var\(--c-drums-ink\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*--tutorial-highlight-rest-shadow:\s*var\(--tutorial-target-contained-rest-shadow\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*--tutorial-highlight-peak-shadow:\s*var\(--tutorial-target-contained-peak-shadow\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*color:\s*var\(--tutorial-target-ink\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*background:\s*var\(--tutorial-target-surface\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*border:\s*1px solid var\(--tutorial-target-surface-border\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*z-index:\s*calc\(var\(--tutorial-target-z\) \+ 3\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*outline-offset:\s*-3px;/s);
  assert.match(css, /\.transport\.tutorial-transport-target\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\s*\{[^}]*background:\s*transparent;/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\s*\{[^}]*box-shadow:\s*none;/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*color:\s*var\(--tutorial-target-ink\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*z-index:\s*calc\(var\(--tutorial-target-z\) \+ 1\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*background:\s*color-mix\(in oklab,\s*white 86%,\s*var\(--tutorial-target-surface\)\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*border:\s*1px solid var\(--tutorial-target-surface-border\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*white 64%,\s*transparent\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*outline-offset:\s*-2px;/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*box-shadow:\s*var\(--tutorial-target-contained-rest-shadow\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*opacity:\s*1;/s);
  assert.doesNotMatch(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*background:\s*transparent;/s);
  assert.doesNotMatch(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*background:\s*var\(--play\);/s);
  assert.doesNotMatch(css, /\.transport\.tutorial-transport-target \.t-btn\.play\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\.active\s*\{[^}]*background:\s*color-mix\(in oklab,\s*white 86%,\s*var\(--tutorial-target-surface\)\);/s);
  assert.match(css, /\.transport\.tutorial-transport-target \.t-btn\.play\.active\s*\{[^}]*box-shadow:\s*var\(--tutorial-target-contained-rest-shadow\);/s);
  assert.doesNotMatch(css, /\.t-btn\.play\.tutorial-control-target/);
  assert.match(css, /\.playhead\.tutorial-playhead-target\s*\{[^}]*animation:\s*tutorial-highlight-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.match(css, /\.playhead\.tutorial-playhead-target\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target\s*\{[^}]*background:\s*transparent;/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target\s*\{[^}]*animation:\s*none;/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target::before,\s*\n\.ruler-playhead\.tutorial-playhead-completed::before\s*\{[^}]*background:\s*transparent;[^}]*box-shadow:\s*none;/s);
  assert.match(css, /\.playhead\.tutorial-playhead-target\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--c-drums-ink\) 86%,\s*white\);/s);
  assert.match(css, /\.playhead\.tutorial-playhead-target\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.match(css, /\.ruler-playhead::after\s*\{[^}]*position:\s*absolute;[^}]*z-index:\s*13;[^}]*left:\s*50%;[^}]*width:\s*16px;[^}]*height:\s*16px;[^}]*border-radius:\s*50%;[^}]*transform:\s*translateX\(-50%\);[^}]*pointer-events:\s*none;/s);
  assert.match(css, /\.ruler-playhead::after\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--brand\) 72%,\s*black\);/s);
  assert.match(css, /\.ruler-playhead::after\s*\{[^}]*border:\s*2px solid color-mix\(in oklab,\s*white 86%,\s*transparent\);/s);
  assert.match(css, /\.ruler-playhead::after\s*\{[^}]*box-shadow:[^}]*0 0 10px/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target::after\s*\{[^}]*background:\s*color-mix\(in oklab,\s*var\(--c-drums-ink\) 88%,\s*black\);/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target::after\s*\{[^}]*border:\s*2px solid color-mix\(in oklab,\s*white 66%,\s*transparent\);/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target::after\s*\{[^}]*outline:\s*2px solid color-mix\(in oklab,\s*white 60%,\s*transparent\);/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target::after\s*\{[^}]*outline-offset:\s*2px;/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target::after\s*\{[^}]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.match(css, /\.ruler-playhead\.tutorial-playhead-target::after\s*\{[^}]*animation:\s*tutorial-highlight-breathe var\(--tutorial-breathe-duration\) var\(--tutorial-breathe-ease\) infinite;/s);
  assert.doesNotMatch(css, /\.playhead-hit\.tutorial-playhead-target/);
  assert.doesNotMatch(css, /\.playhead\.tutorial-playhead-target::after/);
  assert.doesNotMatch(css, /@keyframes tutorial-playhead-pulse/);
  assert.match(css, /@media\s*\(prefers-reduced-motion:\s*reduce\)\s*\{[\s\S]*\.tutorial-target-active,[\s\S]*\.tutorial-cell-target,[\s\S]*\.tutorial-cell-source,[\s\S]*\.tutorial-bar-target,[\s\S]*\.tutorial-control-target,[\s\S]*\.playhead\.tutorial-playhead-target,[\s\S]*\.ruler-playhead\.tutorial-playhead-target::after[\s\S]*animation:\s*none;/s);
  assert.match(css, /@media\s*\(prefers-reduced-motion:\s*reduce\)\s*\{[\s\S]*\.drum-step\.tutorial-cell-source::before\s*\{[^}]*animation:\s*none;/s);
  assert.match(css, /@media\s*\(prefers-reduced-motion:\s*reduce\)\s*\{[\s\S]*box-shadow:\s*var\(--tutorial-highlight-rest-shadow\);/s);
  assert.match(css, /@media\s*\(prefers-reduced-motion:\s*reduce\)\s*\{[\s\S]*\.tutorial-panel-header::before[\s\S]*animation:\s*none;/s);
});

test('clip name edit icon sits beside the shared clip name input', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.clip-name-field\s*\{[^}]*display:\s*inline-flex;/s);
  assert.match(css, /\.clip-name-field\s*\{[^}]*align-items:\s*center;/s);
  assert.match(css, /\.clip-name-edit-icon\s*\{[^}]*flex:\s*0 0 auto;/s);
  assert.match(css, /\.clip-name-edit-icon\s*\{[^}]*pointer-events:\s*none;/s);
});

test('add chord panels keep enrich and passing picker layout without diatonic UI', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.chord-variants\s*\{[^}]*position:\s*fixed;/s);
  assert.match(css, /\.chord-variants\s*\{[^}]*z-index:\s*50;/s);
  assert.match(css, /\.chord-variants\s*\{[^}]*width:\s*min\(760px,\s*calc\(100vw - 32px\)\);/s);
  assert.match(css, /\.app-main:has\(\.tutorial-panel\) \.chord-variants\s*\{[^}]*z-index:\s*var\(--tutorial-floating-ui-z\);/s);
  assert.doesNotMatch(css, /\.app-main:has\(\.tutorial-panel\) \.chord-variants\s*\{[^}]*width:/s);
  assert.match(css, /\.cv-title\s*\{[^}]*font-size:\s*15\.5px;[^}]*font-weight:\s*800;/s);
  assert.doesNotMatch(css, /\.cv-tabs\s*\{/);
  assert.doesNotMatch(css, /\.cv-tab/);
  assert.match(css, /\.cv-panel\[hidden\]\s*\{[^}]*display:\s*none !important;/s);
  assert.doesNotMatch(css, /\.cv-grid\.diatonic/);
  assert.match(css, /\.cv-grid\.enrich\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.cv-context\s*\{[^}]*display:\s*flex;/s);
  assert.match(css, /\.cv-context\.enrich\s*\{[^}]*gap:\s*8px;/s);
  assert.match(css, /\.cv-context\.enrich \.cv-ctx-chord\s*\{[^}]*flex:\s*0 1 auto;[^}]*min-width:\s*0;/s);
  assert.match(css, /\.current-chord-preview\s*\{[^}]*flex:\s*0 0 auto;/s);
  assert.match(css, /\.cv-empty\s*\{[^}]*border:\s*1px dashed var\(--border\);/s);
  assert.match(css, /\.cv-preview\s*\{[^}]*width:\s*28px;[^}]*height:\s*28px;/s);
  assert.match(css, /\.cv-grid\.passing\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\);/s);
  assert.match(css, /\.passing-variants \.cv-card\s*\{[^}]*height:\s*100%;/s);
  assert.doesNotMatch(css, /\.passing-variants \.cv-card\s*\{[^}]*min-height:\s*168px;/s);
  assert.doesNotMatch(css, /\.passing-variants \.cv-card\s*\{[^}]*padding:\s*18px;/s);
  assert.match(css, /\.passing-variants \.cv-foot\s*\{[^}]*flex-direction:\s*row;[^}]*align-items:\s*center;/s);
  assert.match(css, /\.passing-variants \.cv-foot\s*\{[^}]*margin-top:\s*auto;/s);
  assert.doesNotMatch(css, /\.passing-variants \.cv-foot\s*\{[^}]*flex-direction:\s*column;/s);
  assert.match(css, /\.passing-variants \.cv-preview\.full-context\s*\{[^}]*display:\s*inline-flex;/s);
  assert.match(css, /\.passing-variants \.cv-preview\.full-context\s*\{[^}]*width:\s*auto;/s);
  assert.match(css, /\.passing-variants \.cv-preview\.full-context\s*\{[^}]*height:\s*28px;/s);
  assert.match(css, /\.passing-variants \.cv-preview\.full-context\s*\{[^}]*border-radius:\s*999px;/s);
  assert.doesNotMatch(css, /\.cv-roman\s*\{/);
});

test('passing chord shortcut anchors over column fifteen without shifting the grid', async () => {
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(css, /\.beat-group\.has-passing \.beat-head\s*\{[^}]*position:\s*relative;/s);
  assert.match(css, /\.beat-group\.has-passing \.beat-head \.add-chord-btn\s*\{[^}]*width:\s*auto;/s);
  assert.match(css, /\.passing-anchor\s*\{[^}]*position:\s*absolute;[^}]*top:\s*50%;[^}]*left:\s*62\.5%;/s);
  assert.match(css, /\.passing-anchor\.tutorial-passing-anchor-target\s*\{[^}]*z-index:\s*var\(--tutorial-target-z\);/s);
  assert.match(css, /\.passing-btn\.tutorial-control-target\s*\{[^}]*color:\s*var\(--tutorial-target-ink\);[^}]*background:\s*color-mix\(in oklab, white 82%, var\(--tutorial-target-surface\)\);[^}]*border:\s*1px solid var\(--tutorial-target-surface-border\);/s);
  assert.match(css, /\.passing-btn\.tutorial-control-target\s*\{[^}]*box-shadow:\s*var\(--tutorial-target-contained-rest-shadow\),/s);
  assert.match(css, /\.add-chord-btn\s*\{[^}]*background:\s*var\(--bg-deep\);[^}]*border:\s*1px solid var\(--border-soft\);[^}]*border-radius:\s*999px;/s);
  assert.match(css, /\.chord-label-segment\s*\{/);
  assert.match(css, /\.add-chord-btn\.variants-open,\s*\.passing-btn\.variants-open\s*\{/);
  assert.doesNotMatch(css, /\.passing-anchor\s*\{[^}]*top:\s*calc\(-1 \*/s);
  assert.doesNotMatch(css, /\.passing-anchor::after\s*\{/);
  assert.doesNotMatch(css, /\.beat-group\.has-passing \.beat-cells::before\s*\{/);
  assert.doesNotMatch(css, /oklch\(70% 0\.16 355 \/ 0\.06\)/);
  assert.doesNotMatch(css, /\.passing-btn\s*\{[^}]*background:\s*var\(--ink\);/s);
  assert.doesNotMatch(css, /\.passing-btn\s*\{[^}]*color:\s*white;/s);
  assert.doesNotMatch(css, /\.passing-btn\s*\{[^}]*border:\s*0;/s);
  assert.doesNotMatch(css, /\.passing-btn\s*\{[^}]*box-shadow:/s);
  assert.doesNotMatch(css, /\.passing-btn svg\s*\{/);
  assert.doesNotMatch(css, /\.passing-anchor\s*\{[^}]*margin/s);
  assert.doesNotMatch(css, /\.passing-btn\s*\{[^}]*margin/s);
});
